# Generated by Django 4.2.6 on 2023-10-07 03:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_description_blog_image_blog_publish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
